# Generated by Django 4.2.30 on 2026-06-16 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardpost',
            name='datePost',
        ),
        migrations.AddField(
            model_name='boardpost',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='boardpost',
            name='dateTimePost',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boardpost',
            name='dateRequested',
            field=models.DateTimeField(),
        ),
    ]
