# Generated by Django 4.2.30 on 2026-06-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_boardpost_datepost_boardpost_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogprofile',
            name='weightKG',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
