# Generated by Django 4.2.30 on 2026-06-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_dogprofile_weightkg'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardpost',
            name='neighborhood',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boardpost',
            name='post_type',
            field=models.CharField(default='walk', max_length=20),
        ),
        migrations.AddField(
            model_name='boardpost',
            name='schedule',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='boardpost',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boardpost',
            name='dateTimePost',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
